name: CI/CD Deploy Dev

on:
  push:
    branches:
      - dev

jobs:
  test-and-deploy-dev:
    runs-on: ubuntu-latest

    env:
      APP_AWS_REGION: ap-northeast-1
      TABLE_NAME: bpl_room_dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest moto

      - name: Run Unit Tests
        run: pytest test_app.py

      - name: Configure AWS Credentials (DEV)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::219930336567:role/github-actions-deploy-dev-role
          role-session-name: github-deploy-dev
          aws-region: ap-northeast-1

      - name: Deploy to AWS (Chalice Dev)
        run: chalice deploy --stage dev
